[options]
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$FeL8PwcgJGQsJWTM.d8bIw$ThfLXd5.BsU4AxZH70kXGqJXl2j8F3R8pJg.zpaKEAT.C3ssPpSt2rmIdgrZaFe/fa0.kRRtBmyRjRdlUj7yKA

